name: bankbhutan

services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bank_bhutan
    ports:
      - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/bank_bhutan?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for-it.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]